# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json


def add_cards(apps, schema_editor):
    Card = apps.get_model("card", "Card")
    with open('cards.json') as card_file:
        cards = json.load(card_file)['cards']

    for card in cards:
        c = Card(
            name=card['name'],
            mana=card['mana'],
            hero=card['hero'],
            card_type=(card.get('category') or card.get('type')).replace('secret', 'spell'),
            card_set=card.get('set').replace('expert', 'classic').replace('naxxramas', 'naxx'),
            rarity=card['quality'],
            text=card.get('description', ""),
            tribe=card['race'] if card['race'] != 'none' else None,
            attack=card['attack'],
            health=card.get('health') or card.get('durability')
        )
        c.save()


def drop_cards(apps, schema_editor):
    Card = apps.get_model("card", "Card")
    Card.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mana', models.SmallIntegerField()),
                ('hero', models.CharField(choices=[('druid', 'druid'), ('hunter', 'hunter'), ('mage', 'mage'), ('paladin', 'paladin'), ('priest', 'priest'), ('rogue', 'rogue'), ('shaman', 'shaman'), ('warlock', 'warlock'), ('warrior', 'warrior'), ('neutral', 'neutral')], max_length=16)),
                ('card_type', models.CharField(choices=[('minion', 'minion'), ('spell', 'spell'), ('weapon', 'weapon')], max_length=16)),
                ('card_set', models.CharField(choices=[('basic', 'basic'), ('classic', 'classic'), ('reward', 'reward'), ('naxx', 'naxx'), ('gvg', 'gvg'), ('brm', 'brm'), ('tgt', 'tgt'), ('loe', 'loe')], max_length=16)),
                ('rarity', models.CharField(choices=[('free', 'free'), ('common', 'common'), ('rare', 'rare'), ('epic', 'epic'), ('legendary', 'legendary')], max_length=16)),
                ('text', models.TextField(blank=True)),
                ('tribe', models.CharField(choices=[('beast', 'beast'), ('demon', 'demon'), ('dragon', 'dragon'), ('mech', 'mech'), ('murloc', 'murloc'), ('pirate', 'pirate'), ('totem', 'totem')], max_length=16, null=True)),
                ('attack', models.SmallIntegerField(null=True)),
                ('health', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(related_name='collection', through='card.Collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set([('user', 'card')]),
        ),
        migrations.RunPython(add_cards, drop_cards)
    ]
